define(function(){return function(){return{version:"2.4",enableDebugMode:function(c){window.onerror=function(a,d,b,f){if("function"===typeof c)c({message:a,script:d,line:b,column:f});else{var e=[];e.push("\u989d\uff0c\u4ee3\u7801\u6709\u9519\u3002\u3002\u3002");e.push("\n\u9519\u8bef\u4fe1\u606f\uff1a",a);e.push("\n\u51fa\u9519\u6587\u4ef6\uff1a",d);e.push("\n\u51fa\u9519\u4f4d\u7f6e\uff1a",b+"\u884c\uff0c"+f+"\u5217");alert(e.join(""))}}},ready:function(c){if(c&&"function"==typeof c){var a=this,
d=function(){c(a)};"undefined"==typeof window.WeixinJSBridge?document.addEventListener?document.addEventListener("WeixinJSBridgeReady",d,!1):document.attachEvent&&(document.attachEvent("WeixinJSBridgeReady",d),document.attachEvent("onWeixinJSBridgeReady",d)):d()}},shareToTimeline:function(c,a){a=a||{};var d=function(b){WeixinJSBridge.invoke("shareTimeline",{appid:b.appId?b.appId:"",img_url:b.imgUrl,link:b.link,desc:b.desc,title:b.title,img_width:"640",img_height:"640"},function(b){switch(b.err_msg){case "share_timeline:cancel":a.cancel&&
a.cancel(b);break;case "share_timeline:confirm":case "share_timeline:ok":a.confirm&&a.confirm(b);break;default:a.fail&&a.fail(b)}a.all&&a.all(b)})};WeixinJSBridge.on("menu:share:timeline",function(b){a.async&&a.ready?(window._wx_loadedCb_=a.dataLoaded||new Function,0<window._wx_loadedCb_.toString().indexOf("_wx_loadedCb_")&&(window._wx_loadedCb_=new Function),a.dataLoaded=function(a){window._wx_loadedCb_(a);d(a)},a.ready&&a.ready(b)):(a.ready&&a.ready(b),d(c))})},shareToWeibo:function(c,a){a=a||{};
var d=function(b){WeixinJSBridge.invoke("shareWeibo",{content:b.desc,url:b.link},function(b){switch(b.err_msg){case "share_weibo:cancel":a.cancel&&a.cancel(b);break;case "share_weibo:confirm":case "share_weibo:ok":a.confirm&&a.confirm(b);break;default:a.fail&&a.fail(b)}a.all&&a.all(b)})};WeixinJSBridge.on("menu:share:weibo",function(b){a.async&&a.ready?(window._wx_loadedCb_=a.dataLoaded||new Function,0<window._wx_loadedCb_.toString().indexOf("_wx_loadedCb_")&&(window._wx_loadedCb_=new Function),a.dataLoaded=
function(a){window._wx_loadedCb_(a);d(a)},a.ready&&a.ready(b)):(a.ready&&a.ready(b),d(c))})},shareToFriend:function(c,a){a=a||{};var d=function(b){WeixinJSBridge.invoke("sendAppMessage",{appid:b.appId?b.appId:"",img_url:b.imgUrl,link:b.link,desc:b.desc,title:b.title,img_width:"640",img_height:"640"},function(b){switch(b.err_msg){case "send_app_msg:cancel":a.cancel&&a.cancel(b);break;case "send_app_msg:confirm":case "send_app_msg:ok":a.confirm&&a.confirm(b);break;default:a.fail&&a.fail(b)}a.all&&a.all(b)})};
WeixinJSBridge.on("menu:share:appmessage",function(b){a.async&&a.ready?(window._wx_loadedCb_=a.dataLoaded||new Function,0<window._wx_loadedCb_.toString().indexOf("_wx_loadedCb_")&&(window._wx_loadedCb_=new Function),a.dataLoaded=function(a){window._wx_loadedCb_(a);d(a)},a.ready&&a.ready(b)):(a.ready&&a.ready(b),d(c))})},generalShare:function(c,a){a=a||{};var d=function(b,c){b.generalShare({appid:c.appId?c.appId:"",img_url:c.imgUrl,link:c.link,desc:c.desc,title:c.title,img_width:"640",img_height:"640"},
function(c){switch(c.err_msg){case "general_share:cancel":a.cancel&&a.cancel(c,b.shareTo);break;case "general_share:confirm":case "general_share:ok":a.confirm&&a.confirm(c,b.shareTo);break;default:a.fail&&a.fail(c,b.shareTo)}a.all&&a.all(c,b.shareTo)})};WeixinJSBridge.on("menu:general:share",function(b){a.async&&a.ready?(window._wx_loadedCb_=a.dataLoaded||new Function,0<window._wx_loadedCb_.toString().indexOf("_wx_loadedCb_")&&(window._wx_loadedCb_=new Function),a.dataLoaded=function(a){window._wx_loadedCb_(a);
d(b,a)},a.ready&&a.ready(b,b.shareTo)):(a.ready&&a.ready(b,b.shareTo),d(b,c))})},addContact:function(c,a){a=a||{};WeixinJSBridge.invoke("addContact",{webtype:"1",username:c},function(c){c.err_msg&&"add_contact:ok"!=c.err_msg&&"add_contact:added"!=c.err_msg?a.fail&&a.fail(c):a.success&&a.success(c)})},showOptionMenu:function(){WeixinJSBridge.call("showOptionMenu")},hideOptionMenu:function(){WeixinJSBridge.call("hideOptionMenu")},showToolbar:function(){WeixinJSBridge.call("showToolbar")},hideToolbar:function(){WeixinJSBridge.call("hideToolbar")},
getNetworkType:function(c){c&&"function"==typeof c&&WeixinJSBridge.invoke("getNetworkType",{},function(a){c(a.err_msg)})},imagePreview:function(c,a){c&&a&&0!=a.length&&WeixinJSBridge.invoke("imagePreview",{current:c,urls:a})},closeWindow:function(c){c=c||{};WeixinJSBridge.invoke("closeWindow",{},function(a){switch(a.err_msg){case "close_window:ok":c.success&&c.success(a);break;default:c.fail&&c.fail(a)}})},openInWeixin:function(){return/MicroMessenger/i.test(navigator.userAgent)},scanQRCode:function(c){c=
c||{};WeixinJSBridge.invoke("scanQRCode",{},function(a){switch(a.err_msg){case "scan_qrcode:ok":c.success&&c.success(a);break;default:c.fail&&c.fail(a)}})}}}()});